version: '3.9'

services:
  react_native:
    build:
      context: .
      dockerfile: .docker/react/Dockerfile
      target: web
      args:
          NODE_ENV: ${NODE_ENV:-development}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS:-0.0.0.0}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME:-host.docker.internal:19000}
    tty: true
    ports:
      - ${EXTERNAL_REACT_PORT_1:-19000}:19000
      - ${EXTERNAL_REACT_PORT_2:-19001}:19001
      - ${EXTERNAL_REACT_PORT_3:-19002}:19002
      - ${EXTERNAL_REACT_PORT_3:-19006}:19006
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home
    healthcheck:
      disable: true

volumes:
  notused:
